# GemStone/S GCI Connection Configuration

# The name of the Stone (e.g., 'gs64stone' or 'stone')
stoneName: "guava_ops"

# Remote Host Authentication (leave as null if running locally or using .netrc)
hostUserName: null
hostPassword: null

# The NetLDI service name (default is usually 'gemnetobject')
hostName: "localhost"
netLDI: "8080"

# GemStone Database Credentials
gsUserName: "SystemUser"
gsPassword: "swordfish"

stoneServer: "localhost"